name: grizzly_plotly
description: Plotly-like interface to build good-looking plots
version: 0.0.1
homepage: https://github.com/grizzly-dart/grizzly_plotly
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  plotly: ^0.7.3

transformers:
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
