name: grizzly_plotly
description: Plotly-like interface to build good-looking plots
version: 0.2.1-dev
homepage: https://github.com/grizzly-dart/grizzly_plotly
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  grizzly_primitives: ^0.2.0

dev_dependencies:
  browser: ^0.10.0
  plotly: ^0.8.0-alpha.1
  grizzly_series: ^0.2.0
  grizzly_stats: ^0.2.0-dev

web:
  compiler:
    debug: dartdevc
